name: express
version: 0.1.6
author: Demis Bellot <demis.bellot@gmail.com>
description: A thin express-js inspired layer around Darts primitive HttpServer APIs with JSON and Jade HTML view engine support
homepage: https://github.com/dartist/express
dependencies:
  args: ">=0.5.20 <0.6.0"
  jaded: ">=0.1.9 <0.2.0"
  ansicolor: ">=0.0.9 <0.1.0"
dev_dependencies:
  unittest: any
  json_client: any