name: express
version: 0.1.4
author: Axel Christ (fork) from Demis Bellot <demis.bellot@gmail.com> (origin)
description: A thin express-js inspired layer around Darts primitive HttpServer APIs with JSON and Jade HTML view engine support
homepage: https://github.com/dartist/express
dependencies:
  args: any
  dartmixins: any
  jaded: any
  json_client: any
  unittest: any