name: express
version: 0.1.3
author: Demis Bellot <demis.bellot@gmail.com>
description: A thin express-js inspired layer around Dart's primitive HttpServer APIs with JSON and Jade HTML view engine support
homepage: https://github.com/dartist/express
dependencies:
  args: any
  dartmixins: any
  jaded: any
  json_client: any
  unittest: any

#  unittest: any